#!/usr/bin/env python

import sys
from subprocess import Popen, PIPE

intf = sys.argv[1]
ns = '-'.join(intf.split('-')[0:-1])
new_intf = intf.split('-')[-1]

cmd = "ip link set netns %s dev %s" % (ns, intf)
Popen(cmd, shell=True, stdout=PIPE, stderr=PIPE).communicate()

cmd = "ip netns exec %s ip link set name %s dev %s" % (ns, new_intf, intf)
Popen(cmd, shell=True, stdout=PIPE, stderr=PIPE).communicate()
